#!/bin/sh

_EXAMPLE_DIR_=`dirname "$0"`

cd ${_EXAMPLE_DIR_}

_BUNDLES_=$1,$2,$3,$4,$5,$6,$7,$8

if [ "${_BUNDLES_}" = ",,,,,,," ]
then
  echo
  echo "Dynamic service examples"
  echo "------------------------"
  echo
  echo "1) Broken lookup (dangling field)"
  echo "2) Broken lookup (one-time lookup)"
  echo "3) Broken lookup (race condition)"
  echo "4) Correct lookup"
  echo "5) Broken listener"
  echo "6) Correct listener"
  echo "7) Standard tracker"
  echo "8) Customized tracker"
  echo

  read -p "Choose an example (1-8): " _BUNDLES_

  echo
fi

mvn clean install "-P${_BUNDLES_}"

cd target/launch

java -jar launcher.jar bundles

