#!/bin/sh

_EXAMPLE_DIR_=`dirname "$0"`
_EXAMPLE_BSN_=org.foo.hello.lifecycle
_EXAMPLE_VER_=1.0

_EXAMPLE_JAR_=${_EXAMPLE_BSN_}-${_EXAMPLE_VER_}.jar

cd ${_EXAMPLE_DIR_}/lifecycle

if [ ! -r ${_EXAMPLE_BSN_}/target/${_EXAMPLE_JAR_} ]
then
  mvn install
fi

exec mvn pax:provision

