#!/bin/sh

_EXAMPLE_DIR_=`dirname "$0"`
_EXAMPLE_BSN_=org.foo.paint
_EXAMPLE_VER_=3.0

_EXAMPLE_JAR_=${_EXAMPLE_BSN_}-${_EXAMPLE_VER_}.jar

cd ${_EXAMPLE_DIR_}

if [ ! -r ${_EXAMPLE_BSN_}/target/${_EXAMPLE_JAR_} ]
then
  mvn install
fi

exec mvn pax:provision

