#!/bin/sh

_EXAMPLE_DIR_=`dirname "$0"`
_EXAMPLE_BSN_=org.foo.main
_EXAMPLE_VER_=2.0

_EXAMPLE_JAR_=${_EXAMPLE_BSN_}-${_EXAMPLE_VER_}.jar

cd ${_EXAMPLE_DIR_}

if [ ! -r ${_EXAMPLE_BSN_}/target/${_EXAMPLE_JAR_} ]
then
  mvn install
fi

cd ${_EXAMPLE_BSN_}

java -jar target/${_EXAMPLE_JAR_} &

